#set -g utf8
#set-window-option -g utf8
#set -g default-terminal 'rxvt-unicode'


set -g set-titles on
set-option -g detach-on-destroy off



set-option -g prefix `
#set-option -g prefix C-a
unbind-key C-b


bind-key C-a last-window
bind-key ` select-pane -t :.+
bind-key tab next-window
bind-key a send-prefix

bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# 0 is too far from ` ;)
set -g base-index 1

bind-key b set-window-option synchronize-panes on
bind-key B set-window-option synchronize-panes off

set-window-option -g mode-keys vi

# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
#set -g mouse on
bind-key m \
  set -g mouse on \;\
  display 'Mouse-mode: on'

bind-key M \
  set -g mouse off \;\
  display 'Mouse-mode: off'

bind "`" send-key "`"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin "tony-sol/tmux-kubectx"

#themes
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'forest'
set -g @tmux_power_theme '#8ae234'
set -g @tmux_power_right_arrow_icon    ''
set -g @tmux_power_left_arrow_icon     ''
set -g @tmux_power_upload_speed_icon   '󰕒'
set -g @tmux_power_download_speed_icon '󰇚'


# Configure the catppuccin plugin
#set -g @catppuccin_flavor "mocha"
#set -g @catppuccin_window_status_style "rounded"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
#run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
